# Account Create Error

USER_NAME_EXIST_ERROR_CODE = 'ERROR-4000'
USER_NAME_NOT_GIVEN_ERROR_CODE = 'ERROR-4001'
PHONE_NUM_EXIST_ERROR_CODE = 'ERROR-4010'
PHONE_NUM_INVALID_ERROR_CODE = 'ERROR-4011'
PHONE_NUM_NOT_GIVEN_ERROR_CODE = 'ERROR-4012'
EMAIL_INVALID_ERROR_CODE = 'ERROR-4020'
EMAIL_NOT_GIVEN_ERROR_CODE = 'ERROR-4021'
VERIFY_EMAIL_NOT_EXIST_ERROR_CODE = 'ERROR-4022'
EMAIL_EXIST_ERROR_CODE = 'ERROR-4023'
OTP_INCORRECT_ERROR_CODE = 'ERROR-4024'
OTP_INEXIST_ERROR_CODE = 'ERROR-4025'
OTP_EXPIRES_ERROR_CODE = 'ERROR-4026'
OTP_TYPE_CHOICE_ERROR_CODE = 'ERROR-4027'
OTP_UID_NOT_GIVEN_ERROR_CODE = 'ERROR-4028'
OTP_UID_BLANK_ERROR_CODE = 'ERROR-4029'
FAVOURITE_NOT_JSON_ERROR_CODE = 'ERROR-4030'
OTP_CODE_NOT_GIVEN_ERROR_CODE = 'ERROR-4031'
OTP_CODE_BLANK_ERROR_CODE = 'ERROR-4032'
OTP_TYPE_NOT_GIVEN_ERROR_CODE = 'ERROR-4033'
OTP_TYPE_BLANK_ERROR_CODE = 'ERROR-4034'
OTP_TYPE_NOT_MATCH_ERROR_CODE = 'ERROR-4035'
OTP_REQUEST_TWICE_ERROR_CODE = 'ERROR-4036'
OTP_REQUEST_TOO_FREQUENT_ERROR_CODE = 'ERROR-4037'
OTP_TYPE_NOT_ALLOW_ERROR_CODE = 'ERROR-4038'
USER_ALREADY_VERIFIED_ERROR_CODE = 'ERROR-4039'
IS_ROOMER_INVALID_ERROR_CODE = 'ERROR-4043'
NOT_USER_OWN_OTP_ERROR_CODE = 'ERROR-4044'
NON_VERIFIED_USER_ERROR_CODE = 'ERROR-4045'
OTP_ALREADY_USED_ERROR_CODE = 'ERROR-4046'

# Update User Password Error
OLD_PASSWORD_DOES_NOT_MATCH_ERROR = 'ERROR-4040'
OLD_PASSWORD_DOES_NOT_PROVIDE_ERROR = 'ERROR-4041'
NEW_PASSWORD_DOES_NOT_PROVIDE_ERROR = 'ERROR_4042'


# Party Room Create Error

RATING_STARS_MIN_ERROR_CODE = 'ERROR-4100'
RATING_STARS_MAX_ERROR_CODE = 'ERROR-4101'
MIN_NUM_USERS_MIN_ERROR_CODE = 'ERROR-4110'
MIN_NUM_USERS_MAX_ERROR_CODE = 'ERROR-4111'
MIN_NUM_GTE_MAX_NUM_USERS_ERROR_CODE = 'ERROR-4112'
MAX_NUM_USERS_MIN_ERROR_CODE = 'ERROR-4120'
MAX_NUM_USERS_MAX_ERROR_CODE = 'ERROR_4121'
DISTRICT_INVALID_CHOICE_ERROR_CODE = 'ERROR-4130'
AREA_INVALID_CHOICE_ERROR_CODE = 'ERROR-4140'
RULE_LIST_NOT_A_LIST_ERROR_CODE = 'ERROR-4150'
VENUE_LIST_NOT_A_LIST_ERROR_CODE = 'ERROR-4151'
ENTERTAIN_LIST_NOT_A_LIST_ERROR_CODE = 'ERROR-4152'
BOARD_GAME_LIST_NOT_A_LIST_ERROR_CODE = 'ERROR-4153'
ADDITIONAL_SERVICE_LIST_NOT_A_LIST_ERROR_CODE = 'ERROR-4154'
BOOKING_METHOD_LIST_NOT_A_LIST_ERROR_CODE = 'ERROR-4155'
DATETIME_NOT_AVAILABLE_NOT_A_LIST_ERROR_CODE = 'ERROR-4156'
NOT_ROOMER_CREATE_ROOM_ERROR_CODE = 'ERROR-4199'

# Update User Favourite Error 
PARTY_ROOM_DOES_NOT_EXIST_ERROR = 'ERROR-4200'
PARTY_ROOM_UID_DOES_NOT_INCLUDE_ERROR = 'ERROR-4201'
PARTY_ROOM_UID_FIELD_EMPTY_ERROR = 'ERROR-4202'
PARTY_ROOM_UID_NOT_IN_USER_FAVOURITES_ERROR = 'ERROR-4203'

# Booking Error
BOOKING_PARTYROOM_DOES_NOT_EXIST_ERROR = 'ERROR-4300'
BOOKING_DATE_INVALID_ERROR = 'ERROR-4301'
BOOKING_START_TIME_GTE_END_TIME_ERROR = 'ERROR-4310'
BOOKING_START_TIME_INVALID_ERROR = 'ERROR-4311'
BOOKING_END_TIME_INVALID_ERROR = 'ERROR-4312'
BOOKING_NUM_USERS_INVALID_ERROR = 'ERROR-4320'
BOOKING_NUM_USERS_INVALID_TYPE_ERROR = 'ERROR-4321'
BOOKING_UNIT_PRICE_INVALID_ERROR = 'ERROR-4330'
BOOKING_TOTAL_PRICE_INVALID_ERROR = 'ERROR-4331'
BOOKING_UNIT_PRICE_INVALID_TYPE_ERROR = 'ERROR-4332'
BOOKING_TOTAL_PRICE_INVALID_TYPE_ERROR = 'ERROR-4333'

# case1 this booking start before an existing booking but end time(including transition time) is overlapped to an existing booking
BOOKING_TIME_CONFLICS_CASE1_ERROR = 'ERROR-4340'
# case2 this booking start within an existing booking period but end after the existing booking
BOOKING_TIME_CONFLICS_CASE2_ERROR = 'ERROR-4341'
# case 3 this booking is within an existing booking time period
BOOKING_TIME_CONFLICS_CASE3_ERROR = 'ERROR-4342'
# case 4 this booking includes an existing booking period
BOOKING_TIME_CONFLICS_CASE4_ERROR = 'ERROR-4343'
BOOKING_CHECK_TIME_PARAMETER_MISSING_ERROR = 'ERROR-4399'

BOOKING_UID_DOES_NOT_EXIST_ERROR = 'ERROR-4350'
BOOKING_UID_TYPE_ERROR = 'ERROR-4351'

# Authorization
CREDENTIALS_INVALID_ERRORS = 'ERROR-4400'

# Review
SINGLE_REVIEW_ONLY_ERROR_CODE = 'ERROR-4500'
REVIEW_BOOKING_DOES_NOT_EXIST_ERROR_CODE = 'ERROR-4501'
BOOKING_NOT_BELONG_USER_ERROR_CODE = 'ERROR-4502'
NO_RELATIVE_BOOKING_FOUND_ERROR = 'ERROR-4503'
REVIEW_DETAIL_NOT_PROVIED_ERROR = 'ERROR_4504'
PARTYROOM_UID_NOT_PROVIED_ERROR = 'ERROR-4505'